"""Explicit documentary review decisions. No candidate auto-selection or network.
Produces the approved input consumed by prepare-v7-11.py.
"""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
S={
'vt_csm':'https://asl.vt.it/csm-centro-di-salute-mentale',
'r3_csm':'https://www.aslroma3.it/dipartimenti/dipartimento-di-salute-mentale/uoc-salute-mentale-distretto-sanitario-municipio-xi/',
'r4_csm':'https://www.aslroma4.it/strutture-sanitarie/strutture-di-salute-mentale',
'colleferro':'https://www.aslroma5.it/dsmdp-dipartimento-di-salute-mentale-e-delle-dipendenze-patologiche/cosa-sono-i-serd/servizio-per-le-dipendenze-patologiche-colleferro/',
'subiaco':'https://www.aslroma5.it/dsmdp-dipartimento-di-salute-mentale-e-delle-dipendenze-patologiche/cosa-sono-i-serd/servizio-per-le-dipendenze-patologiche-subiaco/',
'npia':'https://www.aslroma5.it/dsmdp-dipartimento-di-salute-mentale-e-delle-dipendenze-patologiche/cosa-sono-le-npia/npia-di-subiaco-e-olevano-romano/',
'qrare':'https://www.qrare.it/','adhd':'https://www.adhdroma.com/contatti/',
'santalucia':'https://www.hsantalucia.it/neuropsicologia','formia':'https://www.ausl.latina.it/dipartimenti/31-azienda/449-dsm',
'iocentro':'https://www.iocentro.it/index.php/contatti/',
'san_carlo':'https://www.ceisroma.it/project/comunita-san-carlo-e-villa-santa-francesca-romana-servizio-residenziale-pedagogico-riabilitativo-per-persone-dipendenti/',
'maieusis':'https://www.maieusis.org/contatti/','samadi':'https://www.ghcspa.com/samadi/contatti',
'rocca':'https://gabbianotirreno.it/strutture/rocca-canterano','castel':'https://gabbianotirreno.it/strutture/castel-madama',
'goito':'https://www.santagostino.it/it/sedi/rm-via-goito','airri':'https://www.airrimedical.it/it/ambulatori-viterbo/',
'rieti_dna':'https://www.asl.rieti.it/iniziative-di-screening-e-prevenzione/'}
P={'version':'7.11','baseline_commit':'85808c6fad9dec32098558e466a3997a18b95d22','checked_at':'2026-09-26','sources':S,'pins':[],'revisions':[],
'reconnaissance':{'queue_records':128,'unique_urls':93,'http_200':68,'coordinate_candidates_records':24,'scope':'Ricognizione automatizzata degli URL; non equivale a validazione manuale di 128 sedi o a conferma telefonica.','source_date_policy':'La data del riesame non sostituisce la data del documento né certifica operatività o disponibilità.'},
'osm_extract':{'url':'https://download.openstreetmap.fr/extracts/europe/italy/lazio-latest.osm.pbf','license':'ODbL-1.0','attribution':'OpenStreetMap contributors','retrieved_at':'2026-09-26T16:12:54Z','last_modified':'Fri, 25 Sep 2026 01:45:47 GMT','sha256':'2c551f007f7839163494048e93446c861d0bbb2e2bfce7b020557ef24e626fcc','bytes':126680950,'features':255907,'boundaries':398}}
def pin(key,source,lat,lng,note,ev,osm=None,quality='C',precision='building'):
 P['pins'].append({'key':key,'source':source,'lat':lat,'lng':lng,'quality':quality,'precision':precision,
 'method':'Confronto manuale fonte del servizio + oggetto OSM in estratto regionale offline del 25/09/2026' if osm else 'Destinazione cartografica pubblicata nella pagina del servizio; escluso il centro della vista della mappa',
 'note':note,'source_url':'https://www.openstreetmap.org/'+osm if osm else S[source],'evidence':ev})
pin('rete:R3-05','r3_csm',41.8554176,12.4451558,'Posizione indicativa dell’edificio di Via Portuense 571; non un ingresso verificato. Non usate le mappe Brisse/Mazzacurati della stessa pagina.',{'selector':'!3d41.8554176!4d12.4451558','publisher_link':'https://www.google.it/maps/place/Via+Portuense,+571,+00149+Roma+RM/@41.8554176,12.4429671,17z/data=!3m1!4b1!4m5!3m4!1s0x13258ab65d84f129:0xbf5ec21afc56aff6!8m2!3d41.8554176!4d12.4451558'})
pin('rete:R4-02','r4_csm',42.07575,11.8143056,'Punto indicativo CSM Civitavecchia, ricavato dal marcatore DMS pubblicato; non attribuito a Morlupo o Campagnano.',{'marker_dms':'42°04’32.7”N 11°48’51.5”E','selector':'etichetta DMS !2z, non !2d/!3d'})
for key,source,lat,lng,link,name in [
('rete:R5-10','colleferro',41.7302976,13.0038841,'TaLpFi7K3ctU6jS69','SerD ASL RM5 Colleferro'),
('rete:R5-12','subiaco',41.932258,13.0863798,'fGGJKta9zNG8NqHt5','Ospedale A. Angelucci'),
('rete:NET-052','npia',41.9246265,13.0919018,'EpWCavzsc23zaxyLA','ASL Distretto Subiaco, Largo Giuseppe Mazzini'),
('rete:NET-053','npia',41.8630775,13.0352554,'NdAG6knZhetVTo576','ASL Poliambulatorio Olevano Romano')]:
 pin(key,source,lat,lng,'Posizione indicativa della sede/complesso collegata dall’ASL al servizio. La stanza, il reparto e l’ingresso fisico non sono verificati.',{'publisher_link':'https://maps.app.goo.gl/'+link,'target_name':name,'selector':'!3d/!4d nella destinazione del redirect, non @lat,lng'})
pin('privati:PRI-004','qrare',41.9123729,12.5152187,'Civico 4 di Viale di Villa Massimo pubblicato dal centro e riscontrato in OSM. Non certifica ingresso o accessibilità.',{'osm_type':'node','osm_id':9691449659,'tags':{'addr:city':'Roma','addr:housenumber':'4','addr:postcode':'00161','addr:street':'Viale di Villa Massimo'},'coordinate_origin':'OSM mapped point'},'node/9691449659','A','address')
pin('privati:PRI-005','adhd',41.845444,12.4809922,'Via Luigi Perna 51, posizione indicativa pubblicata dal centro. Non certifica l’ingresso o la disponibilità di appuntamenti.',{'target_name':'Via Luigi Perna 51','selector':'!3d41.845444!4d12.4809922'})
for key,source,lat,lng,osm,name,note in [
('rete:VT-03','vt_csm',42.6255597,12.1008315,'node/8431382119','Casa della Salute','Casa della Salute Bagnoregio: posizione del presidio, non dello specifico ambulatorio CSM; civico/ingresso non verificati.'),
('rete:VT-09','vt_csm',42.5683524,11.8201472,'node/3503874861','ASL VT1 Consultorio Familiare','Presidio ASL in Via delle Mura 28 a Valentano; mappato il presidio condiviso, non l’ingresso del CSM.'),
('rete:VT-10','vt_csm',42.4604088,12.3843922,'node/1818883486','Centro Salute Orte','Centro Salute/Ospedale di Orte collegato dalla fonte ASL; punto del presidio, non ingresso dell’ambulatorio.'),
('rete:VT-17','vt_csm',42.292384,12.212152,'way/23274363',"Ospedale Sant'Anna",'Complesso Ospedale Sant’Anna Ronciglione, civico 17; OSM usa Via dell’Ospedale Consorziale. Non è verificato l’ingresso del CSM.'),
('privati:PRI-011','santalucia',41.8411765,12.514307,'way/226528209','Fondazione Santa Lucia','Complesso Fondazione Santa Lucia, non ingresso dell’ambulatorio. La scheda mantiene il percorso privato: nessuna promozione automatica del regime SSN.'),
('rete:NET-085','formia',41.2617916,13.6182823,'way/128797276','Dono Svizzero','Edificio ospedaliero Dono Svizzero, documentato come sede SPDC; reparto e ingresso non verificati. Non esteso al SerD che indica soltanto Via Appia.')]:
 typ,ident=osm.split('/');pin(key,source,lat,lng,note,{'osm_type':typ,'osm_id':int(ident),'name':name,'coordinate_origin':'OSM mapped point' if typ=='node' else 'OSM geometry representative point'},osm)
pin('moduli:MOD-087','iocentro',41.8976215,12.5331143,'Via di Pietralatella: breve strada cartografata di circa 70 metri. La fonte indica SNC: il punto è sulla via, non sull’edificio o sull’ingresso.',{'osm_type':'way','osm_id':210674874,'tags':{'highway':'service','name':'Via di Pietralatella','service':'alley'},'coordinate_origin':'OSM geometry representative point'},'way/210674874',precision='street')
def rev(key,source,fields,note,date=None,status='aggiornamento_per_campo'):
 P['revisions'].append({'key':key,'source':source,'fields':fields,'note':note,'status':status,'source_date':date})
rev('rete:R3-05','r3_csm',{'accesso':'Primo contatto con il CSM: accoglienza e valutazione della domanda; contattare la sede per modalità aggiornate.','orari':'Lun 13–20; mar 08–18; mer–ven 08–15'},'Rimosso dal campo accesso il riferimento ad Acilia, estraneo a questa sede. L’avviso di sospensione del 6–7 febbraio 2026 è datato: non è trattato come chiusura corrente.')
rev('rete:R5-10','colleferro',{'telefono':'06 97206760 (infermieri); 06 97206770 (medici); 06 97206764 (responsabile)','accesso':'Accesso diretto e gratuito oppure appuntamento telefonico/e-mail; per il bacino territoriale indicato dall’ASL. Documento di riconoscimento e tessera sanitaria.','sede_dettaglio':'Ingresso indicato dalla pagina ASL su Via Santo Stefano; punto cartografico indicativo, non ingresso fisico verificato.'},'Numeri distinti per funzione e modalità del primo contatto ricontrollati; orari di somministrazione farmaci non confusi con quelli del ricevimento.')
for key in ['rete:NET-052','rete:NET-053']:
 rev(key,'npia',{'accesso':'Primo contatto diretto, senza impegnativa né ticket. Richiesta tramite tsmree.subiaco@aslroma5.it o 0774 8115374; specialisti su appuntamento.','orari':'Telefono per prima visita: lunedì 10:00–12:00; mercoledì 15:00–16:30. Sono fasce di prenotazione, non orari generali di apertura.'},'Orari riferiti esclusivamente al primo contatto; pagina ASL comune alle due sedi. Nessun dato personale raccolto dal portale.')
rev('privati:PRI-004','qrare',{'sede':'Viale di Villa Massimo, 4, Roma','contatti':'376 2715110; prenotazione tramite il centro'},'Sostituita l’indicazione generica della sede con l’indirizzo pubblicato dal centro. Non riesaminati costi, autorizzazione o accreditamento.')
rev('privati:PRI-005','adhd',{'sede':'Via Luigi Perna, 51, Roma','contatti':'353 3985514','email':'info@adhdroma.com'},'Recapiti di contatto del centro pubblicati sul sito del gestore. Nessuna valutazione indipendente di qualità clinica.')
rev('moduli:MOD-087','iocentro',{'indirizzo':'Via di Pietralatella SNC, Roma','telefono':'06 4382379; 347 4728757','orari':'Contatti e appuntamenti: lunedì–venerdì 10:00–18:00','email':'ilcentroonlus@gmail.com'},'Sede del centro documentata dal gestore; non prova di aggiornamento del contratto della singola unità. Il rapporto SSN resta quello precedente.')
rev('rete:NET-085','formia',{'nota_indirizzo':'Sede SPDC nel Dono Svizzero documentata dall’ASL. V7.11 localizza il solo edificio ospedaliero; stanza, reparto e ingresso non verificati.'},'Superata soltanto la nota geografica V7.9.4 di assenza del pin; il livello resta indicativo.')
for key,phone,hours in [
('rete:VT-03','0761 1860426','Lun e ven 09–13:30'),('rete:VT-04','0761 338594','Gio 09–13'),('rete:VT-08','0761 338817','Lun e gio 09–13:30'),('rete:VT-09','0763 711205 / 0761 1860450','Lun e mer 09–13:30'),('rete:VT-10','0761 338214','Mar 08–14'),('rete:VT-13','0761 678555 / 0761 678591','Mar e gio 09–13:30'),('rete:VT-15','0761 569089','Gio 09–13:30'),('rete:VT-17','0761 651298','Lun e mer 09–13:30'),('rete:VT-18','0761 338806','Lun–ven 08–20; sab 08–14')]:
 rev(key,'vt_csm',{'telefono':phone,'orari':hours},'Recapiti e fasce orarie confermati nel documento ASL disponibile, con data di pagina 16/04/2025. Consultazione nel 2026 non equivale a nuova data di validità; riconfermare prima di recarsi alla sede.','2025-04-16','riscontro_documentale_senza_variazione')
rev('moduli:MOD-059','san_carlo',{'nota_indirizzo':'La pagina del gestore documenta Comunità San Carlo in Via Alessandro Volta 2, Marino. La scheda storica include anche Villa Santa Francesca Romana: identità/unità da riconciliare; nessun indirizzo o pin unico attribuito all’intera denominazione.','nota_contatti_v711':'Per la sola Comunità San Carlo: 06 93660116; s.carlo@ceis.it. Non estesi automaticamente all’altra denominazione storica.'},'Conservato il record e la sua identità storica; informazioni nuove limitate alla componente nominativamente documentata. Nessuna fusione/splitting automatico.')
rev('moduli:MOD-083','maieusis',{'indirizzo':'Via Macchia Tonda, 8, Capena','telefono':'06 90389343; 06 36308629 (informazioni e prenotazioni)','email':'maieusis.ct@gmail.com','nota_indirizzo':'Sede residenziale di Capena distinta dal centro diurno in Via Filippo Turati 2/4, Fiano Romano. Nessun pin ricavato dalla sede generica in calce al sito.'},'Differenziate sede residenziale e centro diurno; nessuna modifica di capacità o classificazione SSN.')
for key in ['moduli:MOD-030','moduli:MOD-031','moduli:MOD-032','moduli:MOD-033']:
 rev(key,'samadi',{'telefono':'06 330141','email':'accettazione@samadi.it','nota_contatti_v711':'Ufficio accettazione: lunedì–sabato 09:00–18:00. Questa fascia riguarda i contatti, non l’assistenza residenziale.'},'Recapito del presidio comune ai moduli già distinti; non estesi gli orari dell’accettazione all’attività clinico-assistenziale.')
for key,source,target in [('moduli:MOD-075','castel','Tabaccheria Senza Filtro'),('moduli:MOD-076','castel','Tabaccheria Senza Filtro'),('moduli:MOD-081','rocca','Falesia di Rocca Canterano'),('moduli:MOD-082','rocca','Falesia di Rocca Canterano')]:
 rev(key,source,{'nota_geografia_v711':'Il collegamento cartografico pubblicato dal gestore rinvia a «'+target+'», non a una destinazione nominativa coerente con questa struttura. Coordinate scartate; nessun pin aggiunto.'},'Controllata la destinazione del link: non utilizzate le coordinate del punto non pertinente.')
rev('rete:NET-065','rieti_dna',{'nota_indirizzo':'Sede da riconfermare: il record precedente indica Palazzo Dosi Delfini, mentre un avviso ASL per l’Open Day dell’11/03/2025 indica il Centro DCA in Via delle Ortensie 28, primo piano. Non è acquisita una prova di trasferimento definitivo; nessun pin attribuito.','nota_geografia_v711':'Conflitto fra indicazione precedente e avviso ASL datato; non selezionata automaticamente una sede attuale.'},'L’avviso datato è prova di quella sede per l’evento, non di chiusura/trasferimento permanente. Verifica diretta con il servizio ancora necessaria.','2025-03-03')
rev('privati:PRI-003','goito',{'sede':'Via Goito 58, 00185 Roma','contatti':'06 84000111; prenotazione tramite il centro','orari':'Orari della sede: lunedì–venerdì 07:15–20:00; sabato 08:15–13:00. Appuntamenti delle singole prestazioni da concordare.'},'Indirizzo e contatto della sede riscontrati nella pagina dedicata; gli orari dei prelievi non sono applicati alle prestazioni psicologiche. Geografia ancora da confermare: non scelto arbitrariamente un civico con suffisso diverso.')
rev('privati:PRI76-003','airri',{'sede':'Via Carlo Cattaneo 46/T, Viterbo','contatti':'0761 227123 (poliambulatorio); 0761 306111 (centro)','nota_geografia_v711':'La sede di Viterbo al 46/T resta distinta dalla sede legale romana. Nessun pin attribuito al civico 46/O o a una generica sede del gruppo.'},'Sede operativa e contatti pubblici riscontrati; nessuna deduzione dell’accreditamento delle singole prestazioni e nessuna nuova coordinata sufficientemente univoca.')
assert len(P['pins'])==15 and len(P['revisions'])==30
(R/'research/v7_11/approved.json').write_text(json.dumps(P,ensure_ascii=False,indent=2)+'\n')
