"""Curated, reproducible documentary overlay; never edits historical datasets."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
D='2026-09-22'; BASE='498195783ca07dff14dd4f3640e7e2fae3598e06'
rows=json.loads(Path('/tmp/baseline-rows.json').read_text())
by={r['key']:r for r in rows}; revisions=[]; additions=[]; operators=[]; sources={}
ND='Non documentato'
def source(url,kind='gestore',document_date=None):
 if url not in sources:sources[url]={'url':url,'kind':kind,'checked_at':D,'document_date':document_date,'verification':'documentale; nessuna chiamata o sopralluogo'}
 return url
def patch(key,fields,url,note='',address=False,kind='gestore',document_date=None):
 assert key in by,key
 urls=[source(u,kind,document_date) for u in ([url] if isinstance(url,str) else url)]
 revisions.append({'service_key':key,'checked_at':D,'sources':urls,'fields':fields,'field_evidence':{k:{'sources':urls,'checked_at':D,'previous_value':by[key]['raw'].get(k),'changed':by[key]['raw'].get(k)!=v} for k,v in fields.items()},'address_evidence':'official' if address else None,'note':note,'scope':'riesame parziale dei soli campi elencati'})
def operator(name,keys,sites,services,urls,outcome,pending=None):
 operators.append({'operator':name,'service_keys':keys,'documented_sites_in_scope':sites,'documented_services_in_scope':services,'sources':[source(u) for u in urls],'outcome':outcome,'pending':pending or [],'checked_at':D})
def add(key,name,entity,site,address,town,province,asl,typ,regime,url,fields=None,kind='gestore'):
 origin,ident=key.split(':',1)
 raw={'id':ident,'nome':name,'denominazione':name,'struttura':name,'ente_id':entity,'struttura_id':site,'servizio_id':ident,'gestore':entity,'indirizzo':address,'sede':address,'comune':town,'provincia':province,'asl':asl,'asl_territoriale':asl,'tipo':typ,'tipologia_modulo':typ,'regime':regime,'ambito':'Psichiatria','telefono':ND,'email':ND,'orari':ND,'accesso':ND,'prenotazione':ND,'destinatari':ND,'criteri_ammissione':ND,'costi':ND,'gratuita':ND,'autorizzazione_stato':ND,'accreditamento_stato':ND,'contratto_ssn_stato':ND,'contratto_periodo':ND,'posti_autorizzati':ND,'posti_accreditati':ND,'posti_contrattualizzati':ND,'posti_disponibili':ND,'accessibilita':ND,'mobilita_intraregionale':ND,'accesso_extraregionale':ND,'stato_servizio':'Sede descritta nelle fonti consultate; operatività non confermata telefonicamente','verifica_documentale':D,'ssn_evidence_v79':'rete-asl' if origin=='rete' else 'da-verificare'}
 if origin=='moduli':raw['id_modulo']=ident
 raw.update(fields or {});raw['fonti_v79']=' | '.join([url] if isinstance(url,str) else url)
 urls=[source(u,kind) for u in ([url] if isinstance(url,str) else url)]
 additions.append({'service_key':key,'origin':origin,'record':raw,'checked_at':D,'sources':urls,'address_evidence':'official','scope':'Nuovo servizio distinto; campi non provati esplicitamente non documentati'})
 return key
B='https://www.aslroma5.it/dsmdp-dipartimento-di-salute-mentale-e-delle-dipendenze-patologiche/'
patch('rete:NET-002',{'indirizzo':'Via Giovanni Martinotti, 20','sede_dettaglio':'Ospedale San Filippo Neri, padiglione A, piano terra','telefono':'06 60102408 (medicheria); 06 60102947 (coordinamento infermieristico)','stato_servizio':'Indirizzo corretto: il precedente riferimento dipartimentale non era la sede del reparto. Nessun trasferimento dedotto.'},'https://www.aslroma1.it/presidi-ospedalieri/reparti/spdc-san-filippo-neri','Correzione di localizzazione, non evidenza di un trasferimento.',True,'asl')
patch('rete:R5-02',{'indirizzo':'Via Colleferro, 71','telefono':'0774 779186','email':'csm.guidonia@aslroma5.it','orari':'Lunedì–venerdì 08:00–20:00; sabato e prefestivi 08:00–14:00.','accesso':'Primo accesso diretto o su invio del medico. Accoglienza e valutazione della priorità; visite programmate secondo indicazioni del CSM, con impegnativa e CUP quando richiesti.','costi':'Accoglienza iniziale gratuita secondo la ASL; eventuali prestazioni successive soggette alle condizioni indicate dal servizio. Non si deduce gratuità dell’intero percorso.'},B+'uos-csm-di-guidonia/','Riesame per campo; nessuna verifica telefonica.',True,'asl')
cd=[('NET-043','Piazza Leone Bernardini, 13','0774 341381','cd.guidonia@aslroma5.it','Lunedì, mercoledì, venerdì 08:00–14:30; martedì e giovedì 08:00–17:30.','centro-diurno-di-guidonia/'),('NET-045','Via Domenico Giuliani, 4','0774 3164864; 0774 3164865','cd.tivoli@aslroma5.it',None,'uoc-csm-subiaco-e-tivoli/centro-diurno-di-tivoli/'),('NET-046','Via Repubblica, snc',None,'cd.subiaco@aslroma5.it',None,'uoc-csm-subiaco-e-tivoli/centro-diurno-di-subiaco/'),('NET-047','Via Porta San Martino, snc','06 95322633; 06 95322634','cd.palestrina@aslroma5.it','Lunedì–venerdì 08:00–15:12 (orario riportato dalla ASL).','uoc-csm-di-colleferro-e-palestrina/centro-diurno-di-palestrina/'),('NET-048','Via degli Esplosivi, 9/b','06 97097711; 06 97097712; 06 97097724','cd.colleferro@aslroma5.it','Lunedì, mercoledì, venerdì 08:00–14:00; martedì e giovedì 08:00–17:30.','uoc-csm-di-colleferro-e-palestrina/centro-diurno-di-colleferro/')]
for ident,addr,tel,mail,hours,url in cd:
 f={'indirizzo':addr,'email':mail}
 if tel:f['telefono']=tel
 if hours:f['orari']=hours
 if ident=='NET-043':f['accesso']='Inserimento su progetto terapeutico-riabilitativo individualizzato concordato fra CSM, centro diurno e persona interessata.'
 if ident=='NET-045':f['accessibilita']='La ASL descrive servoscala e bagno per persone con disabilità; fruibilità concreta da confermare con il servizio.'
 if ident=='NET-047':f.update(accesso='Utenti adulti in carico al CSM, su progetto terapeutico individualizzato.',accessibilita='La ASL descrive locali al piano terra e bagni per persone con disabilità; fruibilità concreta da confermare.')
 note=''
 if ident=='NET-046':note='Telefono non aggiornato: la pagina riporta numerazioni che coincidono con Tivoli e stringhe abbreviate; possibile incongruenza da chiarire con la ASL.';f['note_contatti']=note
 patch('rete:'+ident,f,B+url,note,True,'asl')
for ident,addr,tel,mail,path in [('NET-040','Via Roberto Faravelli, 27','06 90075845; 06 90075851','spdc.monterotondo@aslroma5.it','monterotondo'),('NET-041','Via Antonio Parrozzani, 3','0774 3164362','spdc.tivoli@aslroma5.it','tivoli'),('NET-042','Piazza Aldo Moro, 1','06 97223390','spdc.colleferro@aslroma5.it','colleferro')]:
 patch('rete:'+ident,{'indirizzo':addr,'telefono':tel,'email':mail},B+'cosa-sono-gli-spdc/uoc-spdc-'+path+'/','I recapiti sono del reparto; gli orari di visita non sono usati come orari di apertura.',True,'asl')
for name,addr,gender in [('Calvino','Via Calvino, 2','femminile'),('Giovagnoli','Via Giovagnoli, 27','maschile')]:
 add('rete:V79-R5-'+name.upper(),'SRSR '+name,'ASL Roma 5','R5-SRSR-'+name.upper(),addr,'Monterotondo','RM','Roma 5','SRSR','Residenziale',B+'srsr-'+name.lower()+'/',{'telefono':'06 90625579 (riferimento CSM, durante il suo orario di apertura)','orari':'Residenza sempre aperta; il numero indicato risponde durante l’orario del CSM, non è una linea di emergenza.','destinatari':'Utenti di genere '+gender+' in carico al CSM di Monterotondo, in condizioni stabilizzate e con progetto di semiautonomia.','accesso':'Inserimento riservato a utenti del CSM, autorizzato dal responsabile del CSM previa relazione.','servizi':'Programma residenziale socio-riabilitativo a bassa intensità assistenziale e semiautonomia.','note':'La ASL precisa che non vi è personale dedicato alla residenza: supervisione giornaliera del personale CSM. Non è un servizio con assistenza continuativa 24 ore.'},'asl')
operator('ASL Roma 5 – campione DSM',['rete:R5-02']+['rete:'+x for x in ['NET-040','NET-041','NET-042','NET-043','NET-045','NET-046','NET-047','NET-048']]+['rete:V79-R5-CALVINO','rete:V79-R5-GIOVAGNOLI'],None,11,[B],'Aggiornati 9 servizi esistenti e aggiunte 2 residenze distinte.',['Telefono CD Subiaco da chiarire','CD Monterotondo non consolidato.'])
rev=[('moduli:MOD-106','Via Moncenisio, 20','comunita-terapeutica-romana/'),('moduli:MS775-REV-CTC1','Via Passo Cavallone, 4','la-comunita-terapeutica-riabilitativa-residenziale-di-capena-ctc-1/'),('moduli:MS775-REV-CTC2','Via Morlupo, 94','la-comunita-terapeutica-riabilitativa-residenziale-di-capena-ctc-2/'),('moduli:MS775-REV-CD','Via Morlupo, 94','il-centro-diurno/')]
for key,addr,path in rev:
 patch(key,{'indirizzo':addr,'ente_id':'REVERIE','struttura_id':'REV-MORLUPO94' if 'CTC2' in key or key.endswith('-CD') else ('REV-ROMA' if key.endswith('106') else 'REV-CTC1'),'servizio_id':key.split(':')[1]},'https://reverie.it/strutture/'+path,'Riconferma documentale sede e separazione dei servizi; non è verifica del contratto né dell’ingresso.',True)
operator('Reverie',[x[0] for x in rev],3,4,['https://reverie.it/strutture/'],'Quattro servizi conservati; CTC2 e CD condividono la sede.',['Contratto/budget per singolo modulo e ingresso fisico non verificati.'])
for ident,addr,tel,mail,site in [('MOD-094','Via San Francesco, 2/a','0776 567403; 0776 567405','dir.san.borgosantommaso@gestivar.it','BORGO-SAN-TOMMASO'),('MOD-095','Via San Francesco, 2/a','0776 567403; 0776 567405','dir.san.borgosantommaso@gestivar.it','BORGO-SAN-TOMMASO'),('MOD-097','Via Montello, 22','0776 567264','dir.san.montello@gestivar.it','MONTELLO')]:
 patch('moduli:'+ident,{'indirizzo':addr,'telefono':tel,'email':mail,'gestore':'Gesti-Var S.r.l.','ente_id':'GESTI-VAR','struttura_id':site,'servizio_id':ident},['https://gestivar.it/le-strutture/','https://gestivar.it/contatti/'],'Recapiti condivisi fra i moduli di Borgo San Tommaso. Il footer abbrevia il civico in 2; intestazione 2/a.',True)
add('moduli:V79-GV-LICIA','Villa Licia – microstruttura residenziale di mantenimento','Gesti-Var S.r.l.','GV-VILLA-LICIA','Via Enrico Toti, 73','Itri','LT','Latina','SRSR di mantenimento','Residenziale','https://gestivar.it/le-strutture/',{'telefono':'0771 1652157','email':'dir.san.villalicia@gestivar.it','posti_dichiarati':'10','autorizzazione_stato':'Il gestore cita autorizzazione G09889 del 24/07/2024; testo del provvedimento non acquisito in questo riesame.','accreditamento_stato':'Il gestore indica in fase di accreditamento; esito successivo da verificare.','contratto_ssn_stato':'Non documentato; nessuna convenzione dedotta dal gestore delle altre sedi.'})
operator('Gesti-Var',['moduli:'+i for i in ['MOD-094','MOD-095','MOD-097','V79-GV-LICIA']],3,4,['https://gestivar.it/le-strutture/'],'Tre moduli esistenti ricondotti al gestore e una nuova sede/servizio autorizzata secondo il gestore.',['Accreditamento e contratto Villa Licia non consolidati.'])
U='https://www.comunitainsieme.com/strutture/'
for i in range(38,48):
 key='moduli:MOD-%03d'%i
 f={'telefono':'0771 736897 (informazioni del gruppo)','email':'info@comunitainsieme.com','ente_gruppo':'Comunità Insieme – Anelli; distinguere Insieme SAS e Progetto Insieme SRL per il singolo atto','servizio_id':key.split(':')[1]}
 note='Riesame dei recapiti generali e inventario multisede; titolare amministrativo del singolo modulo da verificare negli atti.'
 if i==38:f['nota_indirizzo']='Conflitto: il riepilogo del gestore indica Via De Gasperi 2; il dato precedente indica 36. Civico da confermare; nessun nuovo pin preciso.'
 if i==45:f['indirizzo']='Via Silvio Pellico, 7/9'
 if i==46:f['indirizzo']='Via Ausente, km 2.750'
 patch(key,f,U,note,i in [45,46])
for name in ['Venere','Marte']:
 add('moduli:V79-INS-'+name.upper(),'Comunità Insieme – SRSR '+name,'Comunità Insieme – Anelli (titolare del modulo da verificare)','INS-'+name.upper(),'Via Ausente – località Cerri Aprano','Santi Cosma e Damiano','LT','Latina','SRSR','Residenziale','https://www.comunitainsieme.com/s-r-s-r-venere-e-marte/',{'telefono':'0771 736897 (informazioni del gruppo)','email':'info@comunitainsieme.com','servizi':'Residenzialità socio-riabilitativa, progetti personalizzati e reinserimento sociale in raccordo con i servizi territoriali.','accesso':'Progetto condiviso con i servizi territoriali; modalità pratiche di invio e ammissione da confermare.','autorizzazione_stato':'Il gestore cita un provvedimento regionale del 09/01/2020; riferimento numerico pubblicato da consolidare sull’atto.','note':'Venere e Marte sono due servizi distinti. Condivisione dello stesso edificio non verificata; civico non documentato. Pagina del gestore con aggiornamento indicato 09/05/2022.'})
operator('Comunità Insieme – gruppo Anelli',['moduli:MOD-%03d'%i for i in range(38,48)]+['moduli:V79-INS-VENERE','moduli:V79-INS-MARTE'],None,12,[U,'https://www.comunitainsieme.com/s-r-s-r-venere-e-marte/'],'Inventario dei 10 moduli precedenti; aggiunti Venere e Marte senza dedurre convenzione.',['Civico Abaton 2/36 in conflitto.','Titolare amministrativo, posti e contratto dei nuovi moduli non consolidati.'])
IP='https://www.alidelponte.com/servizi'
patch('moduli:MOD-109',{'denominazione':'Il Ponte / Le Ali del Ponte – Accoglienza residenziale','indirizzo':'Via Amba Aradam, 25','gestore':'Le Ali del Ponte Cooperativa Sociale (servizi descritti dal gestore); collegata all’Associazione Il Ponte','ente_id':'LE-ALI-DEL-PONTE','struttura_id':'PONTE-AMBA25','servizio_id':'PONTE-ACCOGLIENZA','telefono':'0766 35780; 0766 500685 (recapiti generali)','email':'segreteria@alidelponte.com','destinatari':'Giovani tra 16 e 22 anni con dipendenze, secondo il programma del gestore.','ssn_evidence_v79':'da-verificare','posti_autorizzati':'Non documentato per singola sede/fase','posti_accreditati':'Non documentato per singola sede/fase','posti_contrattualizzati':'Non documentato per singola sede/fase','posti_dichiarati':'Non documentato per singola sede/fase','contratto_ssn_stato':'Evidenze del programma conservate nello storico; attribuzione alla singola sede/fase e contratto corrente da verificare.','accreditamento_stato':'Evidenza del programma non automaticamente attribuibile alla singola sede/fase; da verificare.','nota_rapporto_ssn':'Il precedente dato aggregato di 24 posti e le evidenze amministrative del programma sono conservati nel confronto storico dell’audit, non attribuiti automaticamente alla sede di accoglienza. Non dimostrano contratti distinti per tutte le sedi e per Coccinella.'},['https://www.ilpontecivitavecchia.it/',IP,'https://www.alidelponte.com/'],'Record storico conservato come fase/sede di accoglienza; nuove unità separate senza duplicarne i posti.',True)
for ident,name,domain,target in [('RES','Comunità residenziale','Dipendenze','Giovani tra 16 e 22 anni con dipendenze, secondo il programma del gestore.'),('COCCINELLA','Coccinella – comunità madri e bambini','Dipendenze','Donne madri con figli in situazioni di rischio, anche con problematiche di dipendenza, secondo il gestore.')]:
 add('moduli:V79-PONTE-'+ident,'Il Ponte / Le Ali del Ponte – '+name,'Le Ali del Ponte Cooperativa Sociale','PONTE-VENETO30C','Via Veneto, 30/c','Civitavecchia','RM','Roma 4','Comunità terapeutico-riabilitativa','Residenziale',[IP,'https://www.ilpontecivitavecchia.it/'],{'telefono':'0766 35780; 0766 500685 (recapiti generali)','email':'segreteria@alidelponte.com','ambito':domain,'destinatari':target,'servizi':name,'note':'Sede e servizio distinti documentati; dettaglio amministrativo/accreditamento e contratto corrente per questa unità non consolidati. I dati di attività 2020 non sono posti autorizzati né disponibilità attuale.','accesso_extraregionale':'Il gestore descrive invii da servizi di diverse regioni per Coccinella; ammissibilità, autorizzazione e copertura del singolo inserimento da verificare.' if ident=='COCCINELLA' else ND})
operator('Il Ponte / Le Ali del Ponte',['moduli:MOD-109','moduli:V79-PONTE-RES','moduli:V79-PONTE-COCCINELLA'],2,3,[IP,'https://www.ilpontecivitavecchia.it/','https://www.alidelponte.com/'],'Chiuso lo split fisico/funzionale: accoglienza, comunità e Coccinella. Via Isonzo/La Formica non aggiunta alla mappa sanitaria residenziale.',['Accreditamento e contratti distinti per unità restano pendenti.'])
patch('moduli:MOD-108',{'telefono':'0766 570859','email':'c.t.lazio@fratellosole.com','indirizzo':'Via dei Normanni, 8/10','ente_id':'COOPERATE','struttura_id':'COOPERATE-SANTA-SEVERA','servizio_id':'FRATELLO-SOLE-RES'},'https://www.cooperate.it/home.html','Contatti della comunità, distinti dalla sede amministrativa di Tolfa.',True)
add('moduli:V79-COOPERATE-FEBO','FEBO – Centro specialistico semiresidenziale','Cooperate Cooperativa Sociale','COOPERATE-FEBO','Piazza Don Cesolini, 19','Bracciano','RM','Roma 4','Centro specialistico semiresidenziale dipendenze','Semiresidenziale',['https://www.cooperate.it/servizi/bracciano.html','https://www.cooperate.it/home.html','https://www.cooperate.it/servizi/bracciano/centro_specialistico_semiresidenziale.html'],{'ambito':'Dipendenze','ambiti_secondari':'Comorbilità psichiatrica indicata dal gestore','telefono':'06 99802432','email':'febo@fratellosole.com','destinatari':'Adulti con problemi di dipendenza, anche con comorbilità psichiatrica; valutazione della struttura.','autorizzazione_stato':'Il gestore cita autorizzazione G08710 del 21/06/2017.','accreditamento_stato':'Il sito del gestore indica in attesa di accreditamento; provvedimento successivo non acquisito.','contratto_ssn_stato':'Non documentato. Non classificato come convenzionato.','costi':'Da verificare: il progetto gratuito descritto dal gestore riporta una proroga fino al 31/12/2019, non prova gratuità corrente.','accesso':'Contattare il centro per valutazione e raccordo con i servizi territoriali; il gestore contempla anche persone non già in carico.'})
operator('Cooperate / Fratello Sole',['moduli:MOD-108','moduli:V79-COOPERATE-FEBO'],2,2,['https://www.cooperate.it/home.html','https://www.cooperate.it/servizi/bracciano.html'],'Aggiornati recapiti della comunità e aggiunto FEBO come struttura non ASL con rapporto SSN non documentato.',['Esito corrente dell’accreditamento FEBO e costi da verificare.'])
for i in [10,11,12]:
 patch('moduli:MOD-%03d'%i,{'indirizzo':'Via Sesto Celere, 16/18/20','telefono':'06 58331065 (recapito generale)','email':'info@resiletizia.it','ente_id':'VILLA-LETIZIA','struttura_id':'LETIZIA-SESTO-CELERE','servizio_id':'MOD-%03d'%i},'https://www.villaletizia.org/','Sito dichiara aggiornamento 08/09/2026; recapiti generali. Le tre unità non vengono fuse.',True)
operator('Villa Letizia',['moduli:MOD-010','moduli:MOD-011','moduli:MOD-012'],1,3,['https://www.villaletizia.org/'],'Confermati tre moduli distinti; recuperato indirizzo della comunità per adolescenti.',['Contratto corrente dei singoli moduli non nuovamente acquisito.'])
for ident,addr,town,tel,site in [('MOD-083','Via Macchia Tonda, 8','Capena','06 90389343','MAIEUSIS-CAPENA'),('MOD-084','Via Filippo Turati, 2/4','Fiano Romano','0765 389943','MAIEUSIS-FIANO')]:
 patch('moduli:'+ident,{'indirizzo':addr,'comune':town,'telefono':tel+' (sede); 06 36308629 (informazioni/prenotazioni)','email':'maieusis.ct@gmail.com','ente_id':'MAIEUSIS','struttura_id':site,'servizio_id':ident},'https://www.maieusis.org/contatti/','Sedi residenziale e diurna mantenute distinte. Linea di prenotazione condivisa.',True)
operator('Maieusis',['moduli:MOD-083','moduli:MOD-084'],2,2,['https://www.maieusis.org/contatti/'],'Verificate entrambe le sedi e i recapiti specifici.')
for i in range(22,29):
 patch('moduli:MOD-%03d'%i,{'indirizzo':'Via Maremmana Inferiore, 102','telefono':'0774 50011 (centralino della struttura)','email':'accettazionesanitaria@collecesarano.com','ente_gruppo':'Kormed – Colle Cesarano','struttura_id':'COLLE-CESARANO-TIVOLI','servizio_id':'MOD-%03d'%i},'https://www.kormed.it/strutture/colle-cesarano/','Recapiti della sede condivisi; capienza totale non ripartita arbitrariamente fra moduli; orari visite non usati come apertura.',True)
operator('Colle Cesarano / Kormed',['moduli:MOD-%03d'%i for i in range(22,29)],1,7,['https://www.kormed.it/strutture/colle-cesarano/'],'Sette moduli preservati, aggiornamento contatti e indirizzo comune.',['Dotazione e contratto per modulo da consolidare su provvedimenti correnti.'])
NU='https://www.nuoviorizzonti.org/wp-content/uploads/2025/01/CartaDeiServizi.pdf'
patch('moduli:MOD-107',{'email_sede_documentata':'piglio@nuoviorizzonti.org','telefono_sede_documentato':'0775 501075 (carta servizi giugno 2021; da riconfermare)','nota_contatti':'La carta servizi caricata nel percorso 2025 è datata giugno 2021. I recapiti correnti del record non sono sostituiti automaticamente con quelli del documento.'},NU,'Nessuna promozione temporale del documento dal nome della cartella.',False,'gestore','2021-06')
patch('moduli:MS775-NO-CASAGIOIA',{'nota_contatti':'Recapito e indirizzo presenti nella carta servizi giugno 2021; il percorso URL 2025 non è la data di revisione del documento.'},NU,'Sede già presente conservata; rapporto contrattuale corrente non dedotto.',False,'gestore','2021-06')
operator('Nuovi Orizzonti',['moduli:MOD-107','moduli:MS775-NO-CASAGIOIA'],2,2,[NU],'Documentate Piglio e Marino nella carta servizi. Cittadella Cielo/Frosinone non automaticamente inserita come ulteriore comunità sanitaria.',['Ricognizione di ulteriori sedi Lazio non conclusiva; carta servizi giugno 2021.','Contatti Piglio discordanti e contratto Casa Gioia da riconfermare.'])
for i in range(111,115):
 patch('moduli:MOD-%03d'%i,{'telefono':'0766 31818 (recapito generale del gestore)','email':'info@mondonuovo.org','ente_id':'MONDO-NUOVO','servizio_id':'MOD-%03d'%i},'https://comunitamondonuovo.it/category/centri-accreditati/','Contatti generali non confusi con recapiti specifici della singola comunità.')
operator('Comunità Mondo Nuovo',['moduli:MOD-%03d'%i for i in range(111,115)],4,4,['https://comunitamondonuovo.it/category/centri-accreditati/'],'Quattro comunità Lazio esistenti riconosciute nel repertorio del gestore; aggiornati contatti generali.',['Civici/chilometriche e recapiti specifici delle sedi da consolidare.'])
operator('Italian Hospital Group',['moduli:MOD-%03d'%i for i in range(71,83)],None,12,['https://italianhospitalgroup.it/'],'Tentata verifica del sito del gestore, accesso non riuscito; nessun dato operativo inventato.',['Indirizzi delle unità Villa Adriana, Castel Madama, Villanova, Villaggio Adriano e Canterano non consolidati.'])
assert len({x['service_key'] for x in revisions})==len(revisions)
out={'version':'7.9','baseline_commit':BASE,'checked_at':D,'method':'Riesame documentale per campo; dichiarazioni gestore distinte da atti. Nessuna disponibilità in tempo reale, telefonata o verifica ingresso.','sources':list(sources.values()),'revisions':revisions,'additions':additions,'operator_audits':operators,'historical_files_changed':False,'directory_policy':{'universita':'Nessun pin aggiunto: sedi di erogazione e appuntamenti da distinguere da sede legale.','scuole':'Nessun pin aggiunto: destinatari e disponibilità annuale da riconfermare.','centri_ascolto':'Restano separati; La Formica/Via Isonzo candidato non confluito nella mappa residenziale.','helpline':'Nessun pin: servizio prevalentemente telefonico.'},'pending_conflicts':[{'service_key':'moduli:MOD-038','field':'indirizzo','reason':'Civico De Gasperi 2 nel sito contro 36 nel dato precedente; nessun pin preciso nuovo.'},{'service_key':'rete:NET-046','field':'telefono','reason':'Numeri della pagina del CD Subiaco sovrapponibili a Tivoli e forma abbreviata; non sostituiti.'}]}
(R/'data/audit_operativo_v7_9.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print('Revisions',len(revisions),'Additions',len(additions),'operators',len(operators),'sources',len(sources))
