"""Curated documentary changes only. Requires the two immutable research artifacts.
It does not infer service activity, a contract or coordinates from a web search.
"""
from pathlib import Path
import json,re,hashlib,sys,fitz,collections,unicodedata
ROOT=Path(__file__).resolve().parents[1]; R=Path(sys.argv[1]); C=Path(sys.argv[2]); DATE='2026-09-22'
BASE='937713935c693dbbe50109e6738063cc0395e192'
rows=json.loads((R/'baseline-rows.json').read_text()); by={r['key']:r for r in rows}
source_index={x['url']:{**x,'root':R} for x in json.loads((R/'source-index.json').read_text())}
source_index.update({x['url']:{**x,'root':C} for x in json.loads((C/'source-index.json').read_text())})
TABLE='https://www.aslroma5.it/wp-content/uploads/2026/07/Strutture-Private-Accreditate-2025-2026.pdf'
INDEX='https://www.aslroma5.it/amministrazione-trasparente/strutture-sanitarie-private-accreditate/'
used={};revisions={};additions=[]
def source(u,pages=None,period=None):
 x=source_index[u];assert x.get('file'),('Source not acquired',u)
 used.setdefault(u,{k:x[k] for k in ['url','retrieved_at','sha256','bytes','status'] if k in x})
 if pages:used[u]['reviewed_pages']=sorted(set(used[u].get('reviewed_pages',[])+pages))
 if period:used[u]['source_period']=period
 return u
source(TABLE,[8],'Elenco 2025–2026, pubblicato luglio 2026')
source('https://www.kormed.it/strutture/colle-cesarano/')
def revise(key,fields,u,note='',pages=None):
 u=source(u,pages);e=revisions.setdefault(key,{'service_key':key,'checked_at':DATE,'fields':{},'evidence':{},'previous_values':{},'sources':[],'note':'','scope':'Riesame documentale dei soli campi elencati; nessuna telefonata o verifica di disponibilità.'})
 for k,v in fields.items():
  e['fields'][k]=v;e['evidence'][k]={'sources':[u],'checked_at':DATE,**({'pages':pages} if pages else {})};e['previous_values'][k]=by[key]['raw'].get(k)
 if u not in e['sources']:e['sources'].append(u)
 if note:e['note']=' '.join(dict.fromkeys([e['note'],note])).strip()
 return e
# Twelve existing modules: five actual physical sites. Historical keys remain stable.
groups=[('Villa Adriana','villa-adriana',range(71,75),'Tivoli','Via Sardegna, 2','0774533942',[4,6,4,6],'SRSR 24h'),('Castel Madama','castel-madama',range(75,77),'Castel Madama','Strada Provinciale, 40/A','077483275',[10,10],'SRSR 24h'),('Villanova','villanova',range(77,79),'Guidonia Montecelio','Via Cialdini, 25','0774324513',[10,6],'SRSR 24h'),('Villaggio Adriano','villaggio-adriano',range(79,81),'Tivoli','Via del Canopo, 6','0774530527',[8,8],'SRTR-e'),('Rocca Canterano','rocca-canterano',range(81,83),'Rocca Canterano','Via della Maddalena, 2','0774822036',[10,10],'SRTR-e')]
for title,slug,ids,town,address,phone,beds,typ in groups:
 website='https://gabbianotirreno.it/strutture/'+slug;source(website)
 for unit,num in enumerate(ids,1):
  key=f'moduli:MOD-{num:03d}';pdf=f'https://www.aslroma5.it/wp-content/uploads/2026/07/Gabbiano-Tirreno-{title.replace(" ","-")}-{unit}.pdf';source(pdf,[2,9,13,22,23,36],'Contratto 01/08/2025–31/12/2026')
  d=fitz.open(source_index[pdf]['root']/source_index[pdf]['file']);t=d[1].get_text();act=' '.join(re.search(r'nr\.\s*(.*?)\(di seguito',t,re.S)[1].split());nsis=re.search(r'codice NSIS\s*([^\s]+)',t)[1].strip('_-')
  text=' '.join(q.get_text() for q in d);assert re.search(r'01/08/2025\s*fino al\s*31/12/2026',text)
  revise(key,{'denominazione':f'Gabbiano Tirreno – {title} {unit} (già IHG)','gestore':'Gabbiano Tirreno S.r.l.','gestore_precedente':'Italian Hospital Group (denominazione nel dato precedente)','ente_id':'GABBIANO-TIRRENO-13969770968','struttura_id':'GABBIANO-'+slug.upper(),'servizio_id':f'GABBIANO-{slug.upper()}-{unit}','codice_nsis':nsis,'accreditamento_stato':'Accreditamento documentato nel contratto ASL: '+act+'.','contratto_ssn_stato':'Contratto ASL Roma 5 acquisito per questa specifica unità.','contratto_periodo':'01/08/2025–31/12/2026; budget 2026 previsto con provvedimento/addendum distinto, non acquisito in questo riesame.','rapporto_ssn':'Contratto individuale con ASL Roma 5 documentato fino al 31/12/2026; non è una verifica di posti liberi.','ssn_evidence_v791':'indicata','pec_amministrativa':'gabbiano.tirreno@pec.it (PEC amministrativa; non recapito per ammissioni)','accesso_extraregionale':'Il budget psichiatria acquisito è riferito ai residenti nel Lazio. Condizioni e autorizzazioni per altri territori da verificare con ASL inviante e struttura; accesso non escluso né garantito da questo dato.'},pdf,'Subentro/denominazione del gestore distinto da trasferimento fisico. I moduli allo stesso indirizzo restano separati.',[2,13,23])
  revise(key,{'indirizzo':address,'comune':town,'provincia':'RM','asl':'Roma 5','tipo':typ,'posti_accreditati':str(beds[unit-1]),'sede_dettaglio':f'Unità {unit}; interno {unit} indicato nell’elenco ASL. Stesso sito fisico, servizio distinto.'},TABLE,pages=[8])
  access=('Tramite CSM di residenza: PTI, valutazione UVM e richiesta di inserimento. Contattare la sede per la lista d’attesa e il percorso corrente.' if typ=='SRSR 24h' else 'Invio da parte dei servizi territoriali e valutazione della struttura; progetto riabilitativo personalizzato con i servizi invianti.')
  revise(key,{'telefono':phone,'sito_ufficiale':website,'accesso':access,'destinatari':('Adulti con disturbi psichiatrici che necessitano di un contesto residenziale protetto e assistenza continuativa.' if typ=='SRSR 24h' else 'Persone con disturbi psichiatrici in fase sub-acuta; idoneità valutata dai servizi e dalla struttura.'),'note_contatti':'Recapito della sede condiviso dai moduli; chiamata di prova non effettuata.'},website)
  if slug=='castel-madama':revise(key,{'nota_indirizzo':'Il gestore indica Via Provinciale 40/A, anche Via Aniene 36. Nessun ingresso fisico verificato; non usare la sede legale milanese come sede sanitaria.'},website)
# Nine ASL listed services whose municipality/address were placeholders.
items=[(61,'Villa Elisa','Via Tiburtina Valeria, 258','Guidonia Montecelio',17,'U00085/2013'),(62,'Villa Letizia','Via Colle Ristretti, 88','Zagarolo',10,'U00090/2013'),(63,'Operiamo Assieme','Via Agrolatino, 112','Labico',10,'U00043/2013'),(64,'Al Colle','Via Cardinale Pietro Parente, 33','San Cesareo',5,'U00046/2013'),(65,'Insieme','Via Cardinale Pietro Parente, 33','San Cesareo',10,'U00047/2013'),(66,'Villa Maddalena','Via Sant’Anna, 26','Castel Madama',20,'U00165/2013'),(67,'La Staffa','Via Francesco d’Assisi, 46','Tivoli',5,'U00418/2013; DG0023/2023'),(68,'Rosaurora','Via Mainello, 10','Gallicano nel Lazio',10,'U00094/2013'),(69,'Comunità Francesco','Via Cavour, 12','Valmontone',10,'U00108/2013')]
for n,title,address,town,beds,act in items:
 key=f'moduli:MOD-{n:03d}'
 revise(key,{'indirizzo':address,'comune':town,'provincia':'RM','posti_accreditati':str(beds),'accreditamento_stato':'Elenco ufficiale ASL Roma 5 2025–2026: '+act+'.','struttura_id':'ASL5-'+re.sub('[^A-Z0-9]+','-',unicodedata.normalize('NFKD',town+'-'+address).encode('ascii','ignore').decode().upper()),'servizio_id':f'ASL5-MOD-{n:03d}'},TABLE,'Indirizzo sanitario dall’elenco ASL, non dalla sede legale del contratto. Al Colle e Insieme condividono il sito ma non il servizio.',[8])
 if n==63:revise(key,{'denominazione':'Operiamo Assieme (denominazione ASL; già Operiamo Insieme nel database)'},TABLE,pages=[8])
 slug=title.replace('Comunità','Comunita').replace(' ','-');pdf=f'https://www.aslroma5.it/wp-content/uploads/2026/07/{slug}.pdf'
 if source_index.get(pdf,{}).get('file'):
  d=fitz.open(source_index[pdf]['root']/source_index[pdf]['file']);t=d[1].get_text();legal=re.search(r'Società/Ente morale\s*(.*?),\s*C\.F\.',t,re.S)[1];legal=' '.join(legal.split());act=' '.join(re.search(r'nr\.\s*(.*?)\(di seguito',t,re.S)[1].split());text=' '.join(q.get_text() for q in d);assert re.search(r'01/01/2025\s*fino al\s*31/12/2026',text)
  revise(key,{'gestore':legal,'ente_id':re.sub('[^A-Z0-9]+','-',legal.upper()),'accreditamento_stato':'Atto citato nel contratto ASL corrente: '+act+'.','contratto_ssn_stato':'Contratto individuale ASL Roma 5 acquisito.','contratto_periodo':'01/01/2025–31/12/2026; corrispettivo 2026 da provvedimento/addendum distinto.','rapporto_ssn':'Contratto SSN specifico del servizio documentato per 2025–2026; disponibilità e quote non verificate.','ssn_evidence_v791':'indicata'},pdf,'Il contratto e l’elenco ASL citano atti di periodi diversi: conservata la provenienza dei singoli campi.',[2,13])
 else:
  revise(key,{'nota_rapporto_ssn':'Accreditamento da elenco ASL documentato. Il contratto 2025–2026 è elencato nell’indice, ma il file non è stato acquisito in questo ciclo; condizioni individuali da riconfermare.','contratto_ssn_stato':'Contratto segnalato nell’indice ASL; documento individuale non acquisito in V7.9.1.','ssn_evidence_v791':'da-verificare','rapporto_ssn':'Struttura accreditata presente nell’elenco ASL; contratto individuale corrente non acquisito, da riconfermare.'},INDEX,'Il mancato download non è prova di assenza di contratto.')
# Colle Cesarano: aggregate capacities are not multiplied into single modules.
for n in range(22,29):
 revise(f'moduli:MOD-{n:03d}',{'indirizzo':'Via Maremmana Inferiore, 102','comune':'Tivoli','nota_posti':'Elenco ASL 2025–2026: STPIT 30, SRTR intensiva 20, SRTR estensiva 20, SRSR H12 20, SRSR H24 70 aggregati. I 70 non sono attribuiti a ciascuna unità; la ripartizione H24 precedente (60 totali) resta da consolidare.'},TABLE,'Capacità aggregata non equivalente a disponibilità in tempo reale. Nessun nuovo modulo ipotizzato per colmare la differenza 60/70.',[8])
# Two Villa Pia modules, same address: different regimens and explicit conflicting capacities.
website='https://gabbianotirreno.it/strutture/villa-pia';source(website)
for code,regime,typ,beds,act in [('RES','Residenziale','Residenziale DCA/DNA',20,'U00211/2013'),('CD','Semiresidenziale','Centro diurno',40,'U00218/2013')]:
 id='V791-GABBIANO-VILLAPIA-'+code
 r={'id':id,'id_modulo':id,'denominazione':'Gabbiano Tirreno – Villa Pia – '+('residenziale DCA/DNA' if code=='RES' else 'centro diurno DCA/DNA'),'gestore':'Gabbiano Tirreno (denominazione della rete sul sito; titolarità amministrativa della singola unità da confermare)','ente_id':'GABBIANO-TIRRENO-RETE','struttura_id':'GABBIANO-VILLA-PIA-PANTANO35','servizio_id':id,'comune':'Guidonia Montecelio','provincia':'RM','asl':'Roma 5','indirizzo':'Via Pantano, 35','tipo':typ,'ambito':'DCA/DNA','regime':regime,'telefono':'0774300869','email':'Non documentato','orari':'09:00–18:00; giorni di apertura non documentati' if code=='CD' else 'Orari per contatti/visite non documentati','sito_ufficiale':website,'destinatari':'Persone con disturbi della nutrizione e dell’alimentazione; criteri di idoneità da valutare con il servizio.','accesso':'Invio da servizi territoriali, specialisti o strutture competenti; successiva valutazione multidisciplinare.','servizi':'Percorso '+regime.lower()+' con interventi psicoterapeutici, medico-nutrizionali, riabilitativi e sostegno alle famiglie.','posti_accreditati':str(beds),'posti_dichiarati':'20','accreditamento_stato':f'Elenco ASL Roma 5 2025–2026: {beds} posti, atto {act}.','autorizzazione_stato':'Voce presente nell’elenco ASL delle strutture autorizzate e accreditate; atto integrale non acquisito.','contratto_ssn_stato':'Convenzione SSR dichiarata dal gestore; specifico contratto della singola unità non acquisito.','ssn_evidence_v791':'dichiarazione','rapporto_ssn':'Convenzione dichiarata dal gestore; accreditamento da elenco ASL, contratto corrente per questa unità da consolidare.','costi':'Non documentato; verificare quote e percorso autorizzato con servizio inviante e struttura.','accesso_extraregionale':'Da verificare con ASL inviante e struttura.','nota_posti':'Il gestore dichiara 20 posti diurni, mentre l’elenco ASL indica 40 accreditati. Discrepanza conservata, non risolta per presunzione.' if code=='CD' else '20 posti nell’elenco ASL e nella pagina del gestore; nessuna disponibilità rilevata.','nota_indirizzo':'Via Pantano 35 concorda fra pagina del gestore ed elenco ASL 2025–2026. Nessun ingresso verificato.','ultima_verifica':DATE,'fonti':TABLE+' | '+website}
 additions.append({'service_key':'moduli:'+id,'origin':'moduli','record':r,'checked_at':DATE,'sources':[TABLE,website],'note':r['nota_posti'],'scope':'Nuovo servizio documentato; nessun sopralluogo o verifica dei posti disponibili.'})
# Nuovi Orizzonti: admissions contact != headquarters != individual community.
contacts='https://www.nuoviorizzonti.org/contatti/';report='https://www.nuoviorizzonti.org/wp-content/uploads/2025/01/Bilancio-sociale-ODV_2025.pdf';source(report,[1,14,15,16,17,18],'Esercizio 2025; pubblicazione indicata agosto 2026')
for key in ['moduli:MOD-107','moduli:MS775-NO-CASAGIOIA']:
 revise(key,{'telefono':'3929040842','sito_ufficiale':contacts,'orari':'Accoglienza comunità (recapito centrale): lun–ven 09:00–13:00 e 14:00–17:00. Non sono gli orari di visita della singola sede.','accesso':'Per informazioni sull’accoglienza in comunità: +39 392 9040842 negli orari pubblicati. L’ammissione alla singola sede e l’eventuale copertura SSN vanno concordate con il servizio inviante e l’équipe.','note_contatti':'Numero centrale dedicato all’accoglienza comunità, non linea diretta della sede. I precedenti recapiti di sede restano tracciati nei valori storici; nessuna chiamata di prova.'},contacts)
 revise(key,{'nota_rete_v791':'Il bilancio sociale 2025 documenta due comunità pedagogico-riabilitative autorizzate/accreditate nel Lazio: Piglio e Marino. Le altre sedi elencate nel Lazio non sono automaticamente comunità sanitarie accreditate.'},report,'Riesame non esteso agli atti SSN precedenti, che restano con le proprie fonti/date. Per Marino la variante Via/Piazza Garibaldi non viene corretta senza atto puntuale.',[1,14])
# Explicit service-state warning rather than silently retaining an apparently open ward.
u='https://www.aslroma3.it/asl-roma-3-dal-15-aprile-chiude-spdc-al-san-camillo-forlanini/'
revise('rete:NET-025',{'stato_servizio':'Sospensione dei ricoveri documentata dal 15/04/2026; riapertura non documentata nelle fonti riesaminate.','accesso':'Prima di un invio contattare il servizio: accettazione, ricovero e cura SPDC sospesi per lavori secondo avviso ASL del 10/04/2026. DH e consulenze PS/reparti indicati come mantenuti.','orari':'Avviso ASL 10/04/2026: Day Hospital e Centro Disturbi della Personalità 08:00–20:00; non sono orari di accettazione SPDC.','nota_stato':'Avviso storico ancora consultabile; non è una conferma telefonica della situazione odierna. La sospensione non è una cessazione definitiva.'},u,'Record e ubicazione conservati. Fonte datata 10/04/2026; data di lettura 22/09/2026, riapertura da verificare.')
# Dedicated ASL Roma 1 pages were reviewed against their actual service text,
# not against related-service menus or the map iframe alone.
asl1=[(2,'Via Plinio, 31','centro-di-salute-mentale-plinio'),(3,'Via Palestro, 39','centro-salute-mentale-via-palestro'),(4,'Via Sabrata, 12','centro-di-salute-mentale-sabrata'),(5,'Via Boemondo, 21','centro-salute-mentale-via-boemondo'),(6,'Via Monte Tomatico, 9','centro-salute-mentale-via-monte-tomatico'),(7,'Via Ugo Farulli, 6','centro-salute-mentale-via-farulli'),(8,'Via di Boccea, 271','centro-salute-mentale-boccea'),(9,'Via Innocenzo IV, 16/B','centro-salute-mentale-innocenzo-iv'),(10,'Via Pietro Gasparri, 21','centro-salute-mentale-gasparri'),(11,'Via Gioacchino Ventura, 60','centro-salute-mentale-ventura'),(12,'Via Antonino Di Giorgio, 19','centro-salute-mentale-di-giorgio'),(13,'Via dei Riari, 48','serd-via-dei-riari'),(14,'Via dei Frentani, 6','serd-via-dei-frentani'),(15,'Via Nomentana, 2/B','serd-nomentana-2b'),(16,'Via di Monte Sacro, 8','serd-via-montesacro'),(17,'Salita della Marcigliana, 27','servizio-dipendenze-marcigliana-serd'),(18,'Piazza Santa Maria della Pietà, 5','serd-s-maria-della-pieta'),(19,'Via Cassia, 472','polo-integrato-salute-mentale-cassia'),(20,'Via Plinio, 31','ambulatorio-plinio-p-i-p-s-m-polo-ovest'),(21,'Via Sabrata, 12','ambulatorio-sabrata-p-i-p-s-m-polo-est')]
for n,addr,slug in asl1:
 revise(f'rete:R1-{n:02d}',{'indirizzo':addr},'https://www.aslroma1.it/presidi-territoriali/'+slug,'Verificato indirizzo nella scheda dedicata; i servizi suggeriti a fondo pagina non vengono attribuiti a questa sede.')
u='https://www.aslroma1.it/presidi-territoriali/serd-via-dei-frentani'
revise('rete:R1-14',{'nome':'Nuove Dipendenze – SerD Via dei Frentani','telefono':'06 6010.5589 / 06 6010.5590','email':'uosnuovedipendenze@aslroma1.it','orari':'Lun, mar, gio 08:00–13:00 e 14:00–19:00; mer 08:00–11:00 e 14:00–19:00; ven 08:00–14:00.','accesso':'Prestazioni gratuite, senza richiesta del medico curante, per i destinatari e residenti indicati dalla ASL.','destinatari':'Residenti ASL Roma 1: uso di sostanze diverse dagli oppiacei entro i 25 anni; gioco d’azzardo e altre dipendenze senza sostanza per tutte le età.','stato_servizio':'Sede corrente indicata in Via dei Frentani 6 nella pagina ASL aggiornata il 07/05/2026.','nota_indirizzo':'Il dato precedente indicava una sede temporanea in Via Palestro 39. La pagina corrente indica Frentani 6; data esatta del cambio di sede non documentata. Entrambi i valori restano tracciati.','sito_ufficiale':u},u,'Non è una nuova unità né un nuovo ID: aggiornamento della stessa UOS Nuove Dipendenze.')
u='https://www.aslroma1.it/presidi-territoriali/polo-integrato-salute-mentale-cassia'
revise('rete:R1-19',{'telefono':'06 6010.5609','orari':'Martedì e giovedì 08:30–12:30 (PUA del Polo).','accesso':'Tramite il PUA di Via Cassia 472, martedì e giovedì 08:30–12:30.','destinatari':'Residenti del Distretto 15 fino a 30 anni, con bisogni complessi in più aree psicopatologiche; valutazione da parte del Polo.'},u,'Pagina ASL aggiornata il 03/10/2025, consultata il 22/09/2026. Non estendere questi orari agli altri servizi co-localizzati.')
for n,phone in [(3,'06 6010.6050'),(4,'06 6010.5919'),(5,'06 6010.6030'),(6,'06 6010.5291 / 06 6010.5292'),(7,'06 6010.5624'),(8,'06 6010.5125'),(9,'06 6010.6090'),(11,'06 6010.6040')]:
 u='https://www.aslroma1.it/presidi-territoriali/'+next(x[2] for x in asl1 if x[0]==n)
 revise(f'rete:R1-{n:02d}',{'telefono':phone},u,'Telefono della scheda dedicata; non il numero RECUP comune nel piè di pagina. Nessuna chiamata di prova.')

# Field-specific prior values remain fully traceable. Do not rewrite global historical dates.
out={'version':'7.9.1','baseline_commit':BASE,'checked_at':DATE,'scope':'Riesame mirato non esaustivo; nessuna verifica clinica, chiamata o sopralluogo.','revisions':list(revisions.values()),'additions':additions}
(ROOT/'data/audit_operativo_v7_9_1.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
manifest={'version':'7.9.1','checked_at':DATE,'sources':list(used.values()),'research_attempts':[{k:v for k,v in x.items() if k in ['url','status','error','sha256','retrieved_at']} for x in source_index.values()],'raw_source_artifacts':[10692995886,10692715958],'raw_documents_republished':False}
(ROOT/'downloads/Fonti_Verificate_V7_9_1.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print('Operational revisions',len(revisions),'additions',len(additions),'used sources',len(used))
