'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const ctx={URL,URLSearchParams,console,document:{readyState:'loading',addEventListener(){}}};ctx.window=ctx;vm.createContext(ctx);const load=p=>vm.runInContext(fs.readFileSync(p,'utf8'),ctx,{filename:p});
load('assets/servizi-data-v7-5-1.js');
for(const [a,d,g] of [['7-9','7_9','79'],['7-9-1','7_9_1','791'],['7-9-2','7_9_2','792'],['7-9-3','7_9_3','793'],['7-9-4','7_9_4','794'],['7-11','7_11','711'],['7-11-1','7_11_1','7111'],['7-11-2','7_11_2','7112'],['7-11-3','7_11_3','7113'],['7-11-4','7_11_4','7114'],['7-11-5','7_11_5','7115'],['7-11-6','7_11_6','7116'],['7-11-7','7_11_7','7117'],['7-16','7_16','716']]){load('assets/audit-data-v'+a+'.js');ctx['LazioAudit'+g].set(read('data/audit_operativo_v'+d+'.json'));}
const D=read('data/portal_data_v7_3.json'),P=read('data/privati_v7_5.json');D.moduli.push(...read('data/multisede_v7_7_5.json').records);const rows=JSON.parse(JSON.stringify(ctx.LazioServices.build(D,P))),by=Object.fromEntries(rows.map(r=>[r.key,r]));load('assets/map-data-v7-16.js');const G=ctx.LazioMapData,geo=read('data/presidi_geo_v7_16.json'),old=read('data/presidi_geo_v7_11_7.json'),v=read('version.json');
assert.equal(rows.length,443);assert.equal(by['rete:R1-01'].address,'Piazza Santa Maria della Pietà, 5 – Pad. 26');assert.equal(by['rete:NET-074'].town,'Frosinone');assert.equal(by['rete:NET-074'].address,'Via A. Fabi, Palazzina P');
const promoted=['rete:R1-01','rete:NET-074','rete:RI-14','rete:NET-065','moduli:MOD-114','privati:PRI76-003'];for(const k of promoted){assert.ok(G.position(by[k],geo),k);assert.equal(geo.records[k].quality,'C');assert.equal(geo.records[k].entrance_verified,false);}
for(const [k,p] of Object.entries(old.records))if(Number.isFinite(p.lat)&&Number.isFinite(p.lng))assert.deepEqual(geo.records[k],p,k);
assert.equal(rows.filter(r=>G.position(r,geo)).length,379);assert.equal(rows.filter(r=>!G.position(r,geo)).length,64);assert.deepEqual(geo.summary.quality,{D:64,A:29,C:350,E:0});assert.equal(G.position(by['rete:R1-09'],geo),null);assert.equal(G.position(by['rete:R2-10'],geo),null);assert.equal(fs.readFileSync('downloads/Coda_Geografia_V7_16.csv','utf8').trim().split(/\r?\n/).length-1,63);assert.equal(v.web_version,'7.16');assert.equal(v.map.localized,379);assert.equal(v.map.unlocated,64);assert.equal(v.indexing_enabled,false);assert.equal(v.clinical_review,false);console.log(JSON.stringify({version:'7.16',localized:379,unlocated:64,queue:63,promoted},null,2));
