/* Deterministic data, provenance and preservation checks. No external requests. */
'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const ctx={URL,URLSearchParams,document:{readyState:'loading',addEventListener(){}}};ctx.window=ctx;vm.createContext(ctx);
function run(p){vm.runInContext(fs.readFileSync(p,'utf8'),ctx,{filename:p});}
run('assets/servizi-data-v7-5-1.js');
for(const v of ['7-9','7-9-1','7-9-2','7-9-3','7-9-4'])run('assets/audit-data-v'+v+'.js');
const D=read('data/portal_data_v7_3.json'),P=read('data/privati_v7_5.json');D.moduli.push(...read('data/multisede_v7_7_5.json').records);
for(const [api,name] of [['79','7_9'],['791','7_9_1'],['792','7_9_2'],['793','7_9_3'],['794','7_9_4']])ctx['LazioAudit'+api].set(read('data/audit_operativo_v'+name+'.json'));
const previous=ctx.LazioServices.build(D,P),oldby=Object.fromEntries(previous.map(r=>[r.key,r]));
run('assets/audit-data-v7-11.js');const a=read('data/audit_operativo_v7_11.json');ctx.LazioAudit711.set(a);
const untouchedInput=JSON.stringify([D,P,a]);const rows=ctx.LazioServices.build(D,P),by=Object.fromEntries(rows.map(r=>[r.key,r]));
const geo=read('data/presidi_geo_v7_11.json'),oldgeo=read('data/presidi_geo_v7_9_4.json'),v=read('version.json'),report=read('downloads/Audit_Geografia_Operativo_V7_11.json');
const map=require('../assets/map-data-v7-11.js');
const tests=[];function test(name,fn){try{fn();tests.push({name,passed:true});}catch(e){tests.push({name,passed:false,error:e.message});}}
test('443 clinical services retain all original stable keys',()=>{assert.equal(rows.length,443);assert.equal(new Set(rows.map(r=>r.key)).size,443);assert.deepEqual(rows.map(r=>r.key),previous.map(r=>r.key));assert.equal(rows.filter(r=>r.origin==='moduli').length,128);assert.equal(rows.filter(r=>r.origin==='privati').length,17);});
test('Operational overlay cannot mutate inputs',()=>assert.equal(JSON.stringify([D,P,a]),untouchedInput));
test('Only approved fields change; classification, SSN and capacity stay identical',()=>{const revisions=new Map(a.revisions.map(e=>[e.service_key,e]));for(const r of rows){const before=oldby[r.key],e=revisions.get(r.key);for(const [k,value] of Object.entries(before.raw)){if(!e||!(k in e.fields))assert.equal(JSON.stringify(r.raw[k]),JSON.stringify(value),r.key+' '+k);}for(const k of ['type','subtype','regime','auth','accreditation','ssn','admin','beds','origin','date','serviceState'])assert.equal(JSON.stringify(r[k]),JSON.stringify(before[k]),r.key+' '+k);if(!e)assert.equal(JSON.stringify(r),JSON.stringify(before));}});
test('Geographic gate yields exactly 330 / 113, not just manifest counts',()=>{assert.equal(rows.filter(r=>map.position(r,geo)).length,330);assert.equal(rows.filter(r=>!map.position(r,geo)).length,113);assert.equal(geo.summary.entrances_verified,0);});
test('Every one of 315 old points and associated evidence is unchanged',()=>{let n=0;for(const [key,p] of Object.entries(oldgeo.records)){if(p.lat!==null){n++;assert.deepEqual(geo.records[key],p,key);assert(map.position(by[key],geo),key);}}assert.equal(n,315);});
test('Exactly 15 formerly unlocated services are newly placed',()=>{const add=Object.keys(geo.records).filter(k=>oldgeo.records[k].lat===null&&geo.records[k].lat!==null);assert.equal(add.length,15);assert.deepEqual(add.sort(),geo.summary.newly_localized_existing.slice().sort());for(const k of add){const p=geo.records[k];assert.match(p.source_url,/^https:\/\//);assert.match(p.address_source_url,/^https:\/\//);assert.equal(p.entrance_verified,false);assert.equal(p.source_address,by[k].address);assert.equal(p.source_town,by[k].town);assert(p.evidence);}});
test('Quality and precision are conservative: A28 C302 D111 E2',()=>{const count=prop=>Object.values(geo.records).reduce((a,p)=>(a[p[prop]]=(a[p[prop]]||0)+1,a),{});assert.deepEqual(count('quality'),{D:111,A:28,C:302,E:2});assert.deepEqual(count('precision'),{none:113,address:65,street:229,building:36});});
test('Unrelated publisher destinations remain unlocated, never silently promoted',()=>{for(const k of ['moduli:MOD-075','moduli:MOD-076','moduli:MOD-081','moduli:MOD-082','moduli:MOD-111','moduli:MOD-112','moduli:MOD-113','moduli:MOD-114','rete:NET-030','rete:NET-037','rete:NET-065','moduli:MOD-059','moduli:MOD-052','moduli:MOD-053'])assert.equal(map.position(by[k],geo),null,k);assert.match(by['moduli:MOD-075'].raw.nota_geografia_v711,/Tabaccheria/);assert.match(by['moduli:MOD-081'].raw.nota_geografia_v711,/Falesia/);});
test('Map viewport centre is not used as Civitavecchia marker',()=>{const p=geo.records['rete:R4-02'];assert.equal(p.lat,42.07575);assert.equal(p.lng,11.8143056);assert.notEqual(p.lng,11.813756488150585);});
test('New private addresses and contact numbers actually reach search records',()=>{assert.match(by['privati:PRI-004'].address,/Villa Massimo, 4/);assert.match(by['privati:PRI-005'].address,/Luigi Perna, 51/);assert.match(by['privati:PRI-003'].address,/Goito 58/);assert.match(by['privati:PRI76-003'].address,/46\/T/);assert.equal(by['privati:PRI-005'].phone,'3533985514');});
test('Contact hours remain distinct from residential care and appointment opening',()=>{assert.match(by['moduli:MOD-030'].raw.nota_contatti_v711,/non l’assistenza residenziale/);assert.match(by['rete:NET-052'].raw.orari,/non orari generali/);assert.match(by['privati:PRI-003'].raw.orari,/Orari della sede/);});
test('30 scoped reviews distinguish 21 changes and 9 confirmations',()=>{assert.equal(a.revisions.length,30);assert.equal(a.additions.length,0);assert.equal(report.records_with_field_changes,21);assert.equal(report.records_confirmed_without_field_change,9);assert.equal(report.fields_compared,67);assert.equal(report.fields_changed,42);for(const e of a.revisions){for(const k of Object.keys(e.fields)){assert(e.evidence[k].sources.length);assert('source_date' in e.evidence[k]);}}});
test('No unsupported administrative field can be injected into the overlay',()=>{const bad=JSON.parse(JSON.stringify(a));bad.revisions[0].fields.accreditamento='invented';assert.throws(()=>ctx.LazioAudit711.validate(bad));});
test('All 128 source-triage records are accounted for, with only 15 promotions',()=>{assert.equal(report.queue_review.length,128);assert.equal(new Set(report.queue_review.map(r=>r.key)).size,128);assert.equal(report.queue_review.filter(r=>r.geography_status==='localizzato_documentalmente').length,15);assert.equal(report.queue_review.filter(r=>r.geography_status==='ancora_senza_pin').length,113);assert.equal(report.reconnaissance.unique_urls,93);assert.equal(report.existing_C_records_rechecked_completely,false);});
test('Historical data, assets and downloads are preserved byte for byte',()=>{for(const [p,hash] of Object.entries(read('downloads/Integrita_Baseline_V7_11.json').sha256))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),hash,p);});
test('Independent clinical safeguards, support and Menta remain unchanged',()=>{assert.equal(v.clinical_review,false);assert.equal(v.indexing_enabled,false);assert.equal(v.web_version,'7.11');assert.equal(v.menta_version,'7.10.3');assert.equal(v.menta_asset_version,'7.10.1');assert.equal(v.student_path_version,'7.10.3');const s=read('data/supporto_territoriale_v7_10.json');assert.equal(s.consultori_master.length,135);assert.equal(s.pua_sites.length,47);assert.equal(s.pis_services.length,6);});
test('All current entrypoints include the new overlay and versioned renderer',()=>{for(const p of ['servizi.html','archivio.html','mappa.html','strutture-approfondite.html','privati.html'])assert(fs.readFileSync(p,'utf8').includes('/assets/audit-data-v7-11.js'),p);assert(fs.readFileSync('mappa.html','utf8').includes('/assets/map-data-v7-11.js'));assert(fs.readFileSync('privati.html','utf8').includes('/assets/directory-v7-11.js'));});
test('The new audit adapter has no network, storage or device-location code',()=>assert(!/fetch\s*\(|XMLHttpRequest|sendBeacon|geolocation|localStorage|sessionStorage/.test(fs.readFileSync('assets/audit-data-v7-11.js','utf8'))));
const result={version:'7.11',tests,passed:tests.filter(t=>t.passed).length,total:tests.length};console.log(JSON.stringify(result,null,2));if(result.passed!==result.total)process.exitCode=1;
