from pathlib import Path
import subprocess
# Third-party distribution retains its exact upstream CRLF bytes.
subprocess.run(['git','config','core.whitespace','cr-at-eol'],check=True)
p=Path('guide/index.html');s=p.read_text();start=s.index('<main');end=s.index('</main>',start);body=s[start:end];body=body.replace('<h3>','<h2 class="guide-card-title">').replace('</h3>','</h2>');p.write_text(s[:start]+body+s[end:])
p=Path('assets/ux-map-v7-8.css');p.write_text(p.read_text()+'\n.guide-card-title{font-size:1.15rem;line-height:1.35;margin:0 0 10px}\n')
p=Path('assets/map-v7-8.js');s=p.read_text();old="box.append(element('strong',group.length>1?group.length+' servizi in questa posizione':'Servizio'));";new="box.append(element('h2',group.length>1?group.length+' servizi in questa posizione':'Servizio'));";assert old in s;s=s.replace(old,new);s=s.replace('{maxWidth:330,maxHeight:310}', '{maxWidth:Math.min(330,Math.max(200,window.innerWidth-100)),maxHeight:mobile()?220:310,autoPanPadding:[24,24]}');p.write_text(s)
p=Path('assets/map-v7-8.css');p.write_text(p.read_text()+'\n.map-popup h2{font-size:1.05rem;line-height:1.4;margin:0 0 8px;color:#163e34}\n#map-chips{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}#map-chips button{min-height:44px;padding:8px 12px;border:1px solid #86ac9e;border-radius:24px;background:#fff;color:#164e47;font:inherit;cursor:pointer}\n.map-page .leaflet-popup-content{overflow-x:hidden}.map-page .leaflet-popup-content h2{padding-right:12px}\n')
p=Path('tools/test-ux-map-v7-8.mjs');s=p.read_text();s=s.replace("for(const name of audit.pages){", "const violations=[];for(const name of audit.pages){");s=s.replace("assert.equal(axe.violations.length,0,name+': '+axe.violations.map(v=>v.id).join(','));", "violations.push(...axe.violations.map(v=>({page:name,id:v.id,nodes:v.nodes.map(n=>n.html)})));");needle="    }\n  });\n  await test('Mobile service search";assert needle in s;s=s.replace(needle,"    }\n    assert.equal(violations.length,0,JSON.stringify(violations));\n  });\n  await test('Mobile service search",1);s=s.replace("await screenshot('mappa-stesso-indirizzo-390.png');", "await p.waitForTimeout(500);await screenshot('mappa-stesso-indirizzo-390.png');");p.write_text('\n'.join(x.rstrip() for x in s.splitlines())+'\n')
print('Heading hierarchy and popup sizing corrected; historical data and vendor bytes unchanged.')
